/// <reference types="vite-plugin-pwa/client" />

import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst, CacheFirst } from "workbox-strategies";
import { clientsClaim } from "workbox-core";

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the Nuxt app
// This is the injection point for the precache manifest
// Don't remove this comment
precacheAndRoute(self.__WB_MANIFEST);

// Cache page navigations
registerRoute(
  ({ request }) => request.mode === "navigate",
  new NetworkFirst({
    cacheName: "pages",
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "images",
  })
);

// Skip waiting so the new service worker activates immediately
clientsClaim();
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});
